### ISSUE TITLE
Team Charter

### ISSUE THREAD

**Issue by Luxo736** [kdea020/metabolomics-project#2]
Could you upload your Team Charter for me to review? Thanks

**Comment by kdea020** [comment]
Will do!

**Comment by kdea020** [comment]
The team charter is now uploaded, Luis.

Sorry for the tardiness and thanks for your patience. Looking forward to your feedback! :)

**Comment by Luxo736** [comment]
**What is good**
I found your mission very precise and simple, also achievable according to your skills.

I like the fact that you place very realistic goals in succes criteria. Specially because your determination to put on practice each of the criteria you mentioned.

I like that you encourage the idea of “no hate speech” as I think is the best way to communicate and idea clear and fast.

**What can be improved**
Even that Project vision is concrete, probably needs to be more specific as “digital reserach skills” may include different areas that might or might not be cover in long term.

In success criteria, mantain good relationships with  supervisor(s), might imply that  that is applicable only for supervisors , so I think it could work better  if you include  classmates as well.

As well,The thing Kieran makes does what he wants it to. This “thing” may have a better deffinition like “functions” or  maybe other more convinient that will define it better.

Maybe  for  my understanding it could sounds different but, be punctual and consistent with attendance (primarily supervisory meetings) . May be better to avoid the phrase in between() as this rest importance for the rest of meetings. However i might be wrong.

“Value the contributions of each team member” and “Credit where credit is due” may possibly have the same meaning?

ASAP might work good for  an informal document ... maybe? I think to avoid abbreviations could give better clarity.

Good job mate!

**Comment by kdea020** [comment]
Thanks Luis! Great feedback, agree with pretty much all the issues you've raised.

And I made sure to include "No hate speech" after your suggestion in class when we were building the class team charter :)

**Comment by kdea020** [comment]
Hey Luis! Can you confirm for me that you're happy with the changes I made in response to your feedback for the "final handshake"? Thanks :)

**Comment by Luxo736** [comment]
Absolutely very well done!
