### ISSUE TITLE
Peer Review of Code 4/10/2016

### ISSUE THREAD

**Issue by CallumChalmers29** [kdea020/metabolomics-project#3]
Hi Kieran,

What is good about main_0-3.R:
- Love the licensing info at the beginning
- Generally extremely well commented, very clear and concise :)
- Very well organised
- Functions are short and generally only do a few tasks which is awesome and makes the programme flow easier
- Citations are impressive

What could be improved in main_0-3.R:
- Lines 72-96 could have more comments 

What is good about project_0-2.R:
- Again commenting and structure is very good as above

What could be improved in main_0-3.R:
- Lines 161-167 could have more comments 
- Lines 214-250 could have more comments 
- Lines 281-287 could have more comments 

What is good about TESTING.R:
- Very clear what is being tested

What could be improved about TESTING.R:
- Nothing

Would also be useful to add documentation as the idea of agile is to have a shippable product at the end of each sprint and the product owner would probably like to know how the programme works. Overall, you have produced an amazing product and even with no knowledge of R, I was able to (mostly) understand what was going on which is awesome. Keep up the good work :)

Callum

**Comment by kdea020** [comment]
Hey Callum, thank you for the amazing feedback! Will add more comments :)

**Comment by kdea020** [comment]
Hi Callum!

I've gone through and altered my project in response to your feedback.

Are you able to go through my changes in the commits for the last two days and ensure meet your expectations for the final handshake?

Many thanks.

**Comment by CallumChalmers29** [comment]
Hi Kieran,

Had a look and it all seems perfect to me, I am happy to close the issue, keep up the great work!

Callum
