### ISSUE TITLE
Peer Review of final assignment 

### ISSUE THREAD

**Issue by BibianaLee** [kdea020/metabolomics-project#7]
Hi Kieran, 

After reading your final assignment I would say that you are heading in the right direction! Your overview, implementation, quality control and reuse potential sections are looking good. The only thing I could possibly pick on right now would be the introduction section. I'm not really from a hard science background so I'm not really familiar with the terms you used in the introduction. I think Callum's final assignment is a good example of how you could maybe make your introduction a bit more explicit for ze average person like me :) 

Overall, you've done an awesome job! 

Kind Regards, 
Bibiana

**Comment by kdea020** [comment]
Thanks heaps for the feedback Bibiana!

Callum has raised the same points in his feedback so making it more accessible has become priority #1. There actually isn't an introduction in that file - it's just the abstract for the paper. The introduction "proper" in the paper itself will elaborate better and make sure things are explained clearly :)

However I have still made some changes to the abstract to make it more understandable for someone without a metabolomics background.

**Comment by kdea020** [comment]
Hi Bibiana,

Just wondering if the changes I have made to my final report are sufficient for you or if you would want to see more response to feedback before a final handshake? :)

**Comment by BibianaLee** [comment]
omg I'M SO SORRY 

Yes looks good errthang looks perfect! You even added a diagram noice!
